### ISSUE TITLE
Active XPPickup marked as hasBeenPickedUp=true

### ISSUE THREAD

**Issue by iZastic** [acr-gaming/20min_lag_less#6]
While trying to make my Buddy mod compatible with yours I noticed that sometimes an XPPickup is marked as hasBeenPickedUp=true but it stays active in the game. This keeps it visible but impossible to pickup by either my mod "Buddy" or the player.

**Comment by acr-gaming** [comment]
https://github.com/acr-gaming/20min_lag_less/pull/7

**Comment by acr-gaming** [comment]
fixed
